### PR TITLE
feat: add support for plexamp

### PR DESCRIPTION
**Pull request by pmdroid**
This merge request adds support for plexamp

### CODE REVIEW

**Comment by pmdroid** [comment]
[create merge request](https://github.com/hifiberry/create/pull/14)

**Comment by hifiberry** [comment]
Thank you. Do you use this with HiFiBerryOS? In this case, it would be good to also have a small guide how to install it

**Comment by pmdroid** [comment]
@hifiberry yes i used HiFiBerryOS, for my testing i pushed my changes onto the machine, i though when this is merged it will be available in HiFiBerryOS?

When both of these pull request are on your machine then you can open the plexamp setting from the HiFiBerryOS sources page to enable and setup plexamp [images](https://imgur.com/a/Lbef4ei)
when the plexamp source is setup it will redirect to the ip of the machine port 32500 und which plexamp is running, there you can login with your plex credentials and assign a name for the instance. when this done you can use plexamp on your phone to controll the music, the metadata is displayed in hifiberry.
volume control, play pause and skip, prev all work when controlled trough plex or hifiberry.
album art is fetched from the used plex server.

**Comment by hifiberry** [comment]
Thank you. I'll have a look into this.

**Pull request merged**
