### PR TITLE
Socketio api

### PR DESCRIPTION
**Pull request by schnabel**
Hi,
this PR implements [this feature request](https://github.com/hifiberry/audiocontrol2/issues/20).
In case you want to see (or run) some tests you could check out [my pyhifiberry fork](https://github.com/schnabel/pyhifiberry/tree/socketio). This package will be used in [the homeassistant plugin](https://github.com/willholdoway/hifiberry) in case you will accept the PR.

### CODE REVIEW

**Comment by schnabel** [comment]
Hi @hifiberry, me and the downstream projects are still looking forward to get some feedback :-).

**Comment by hifiberry** [comment]
Sorry for the delay on this. Unfortunately your code requires extra modules that are not available in buildroot. Did you do the development/testing on HiFiBerryOS? If yes, do you have a patch with these modules?

**Comment by schnabel** [comment]
Hi, I did most of the development/testing on my Desktop (ubuntu 21.10). I offered a PR for HiFiBerryOS [here](https://github.com/hifiberry/hifiberry-os/issues/313) :-). In case you prefer to test on HiFiBerryOS I will need to check if my patch is still up to date.

**Comment by hifiberry** [comment]
Yes, please send you PR as we need to test this on HiFiBerryOS (it's ok if others use it on other systems, but for us it's most important that it builds and works on HBOS). When you have the PR ready, le me know and I can test.
It will take some time anyway for a new HBOS release as we're just in the process of upgrading to buildroot 2021-11

**Comment by schnabel** [comment]
Great. It is OK than if the PR is based on buildroot 2021-11?!

**Comment by hifiberry** [comment]
That's ok. However, you might notice that it doesn't yet build on buildroot 2021-11. We're still working on this.

**Comment by schnabel** [comment]
@hifiberry I just wanted to check if you have been able to test my hifiberry-os patch yet :-).

**Comment by hifiberry** [comment]
See my comment on the Pull request

**Comment by hifiberry** [comment]
Just noticed that the patch in incompatible with the "keyboard" module. It seems gevent and keyboard don't work together. Have you enabled the keyboard plugin?

**Comment by schnabel** [comment]
Thanks a lot for your support!!!
Did you have trouble with keyboard and gevent, or are you referring to what I wrote [here](https://github.com/hifiberry/audiocontrol2/issues/20#issuecomment-1036067138)?

**Comment by hifiberry** [comment]
The keyboard module hangs when using this patch. My guess is that it is an incompatibility with gevent. gevent might be blocking access to the keyboard. But that's just a guess.
With the keyboard module enabled, the server just hangs during startup in the keyboard module initialisation.

**Comment by schnabel** [comment]
I case I can help ... let me know.

**Comment by hifiberry** [comment]
Yes, please find a fix or workaround. As long as this isn't fixed we can't include this patch. Best is probably to find a way to get both modules to coexist (I don't know the gevent module in detail, but there might be some way to configure it not to attach to keyboard events). Alternatively you could rewrite the keyboard input module to use gevent instead of keyboard. 
Unfortunately I don't have the time to dig into this.

**Comment by schnabel** [comment]
I did a lot of digging this weekend :-(. I found the place where things go wrong with the keyboard package when gevent.monkey.patch_all() is used. I created an [issue](https://github.com/gevent/gevent/issues/1871) and hope for a fix or a tip on what to do.
Something else we could do is to use pynput instead of keyboard. It seems to behave well with gevent and it has another big advantage over keyboard. It does not require the process to be run as root (this would have been a showstopper for me to use keyboard in the first place). Would you accept a rewrite of the keyboard plugin with pynput in case the gevent guys cannot help?

**Comment by hifiberry** [comment]
Yes, using another module is just fine as long as the keyboard module still used the same configuration file syntax.

**Comment by schnabel** [comment]
Ok. Great, but I will wait a few days for an answer from the gevent side before I start with this option.

**Comment by schnabel** [comment]
Is it correct that there is no documentation/test for the keyboard configuration file syntax or have I missed it?

**Comment by hifiberry** [comment]
No, there are no tests or specific configuration. To test it, just connect a keyboard. With the standard configuration, cursor left/right should skip backward/forward and enter should play/pause

**Comment by schnabel** [comment]
Yes, I got that from the code :-). I was just wondering if there is anything else to watch out for since you mentioned the config file.
I had a look pynput and had to learn that it needs root on headless linux, too.
Is it a requirement that audiocontrol2 can be run on win and macos? I think a read that somewhere. I am asking because otherwise I could use evdev.

**Comment by hifiberry** [comment]
While in general it might be nice to run on other systems, I don't think there is someone really doing this. Therefore, a pure Linux version of the keyboard module should be just fine.

**Comment by schnabel** [comment]
The gevent guys have not answered yet. So I started with the refactoring of the keyboard module.
Do you want me to open an issue for it?

**Comment by hifiberry** [comment]
No need for an issue, just send the Pull when it's ready.

**Pull request merged**
